services:
  app:
    build: .
    container_name: antar
    networks:
      - cloudcart-net
    restart: unless-stopped
    environment:
      - PORT=80

networks:
  cloudcart-net:
    external: true
